### ISSUE TITLE
Downloading does not work

### ISSUE THREAD

**Issue by mokasin** [bottiger/SoundWaves#72]
Downloading episodes does not work for me. I've tried different podcasts. The farest I got: A download was completed but apparently not saved (immediately after it I can restart the download). Playing episodes works just fine.

Which information do you need? Then I can try to provide it.

I'm on Android 5.1.1 Xperia Z3

**Comment by bottiger** [comment]
@mokasin I'm taking a wild guess here. But it sounds like the app successfully downloads the file, but fails to store it in the device.

It is not something I have heard of before, but I will start investigating potential causes.

**Comment by mokasin** [comment]
@bottiger I've installed the update. Download works, but apparently it still does not stores the file. 
How do I provide for the log?

**Comment by bottiger** [comment]
@mokasin I send's a crash report automatically. However, it seems that the problem was not what I thought it was.

I will create a new version with some extended logging, but it may take a day or two.

**Comment by bottiger** [comment]
@mokasin Can I e-mail you a special build for testing?

**Comment by mokasin** [comment]
Sure, just send it to my Github Email alias.

**Comment by bottiger** [comment]
@mokasin Grab this one: https://www.dropbox.com/s/oxpjg7iarkyilzk/SoundWaves128.11.apk?dl=1

It should be signed with the same key as the one on google play, therefore just replacing it. Also, when I update the app one Google play this one will be overwritten.

Anyhow. Try to download a file. Afterwards there should be a folder called "SoundWavesDebug" in the root directory of you phones storage. The folder should contain a log file with some information of what is going on.

**Comment by mokasin** [comment]
I could not locate a file with that name. But I have found full downloaded episodes in the Android/data/.../files/tmp. I'm on my phone, so it's a bit cumbersome to check myself: Are you,by any chance,  trying to move the files elsewhere? Are you aware, that since Android 4.4 an app is not allowed to write outside specific folders? It has to go through the Storage Access Framework.

See http://m.androidcentral.com/kitkat-sdcard-changes

https://developer.android.com/guide/topics/providers/document-provider.html
http://developer.android.com/guide/topics/data/data-storage.html

https://source.android.com/devices/storage/

Am 19. März 2016 20:55:45 MEZ, schrieb "Arvid Böttiger" <notifications@github.com>:

**Comment by bottiger** [comment]
@mokasin I is true that the files are first downloading to a tmp folder and the moved to the ["Podcast" directory](http://developer.android.com/reference/android/os/Environment.html#DIRECTORY_PODCASTS). I am aware that different versions of Android have very different permission models for writing files outside the app folder, but the podcast directory should (as far as I remember) be open.

However, there is obviously a problem here :) Which version of Android are you running and which phone are you using?

**Comment by bottiger** [comment]
@mokasin I've tested downloading on various version of Android without being able to reproduce the problem so far.

**Comment by mokasin** [comment]
It's on Android 5.1.1 on a Sony Xperia Z3. Does writing the log file into the phone storage root then works? Or have I looked at the wrong place?

I'm going to look at the logcat. Maybe I'll find something.

**Comment by bottiger** [comment]
@mokasin It does write everything into logcat. Just filter on the string "OkHttpDownloaderLog"

**Comment by bottiger** [comment]
@mokasin I finally found a bug which probably caused this error. It should start propagating out now. Please let me know if it works for you.

**Comment by mokasin** [comment]
@bottiger At least, I was able to play a stream I've previously downloaded. But there is still no indication, that it was downloaded. And it still resides in the above mentioned tmp folder.

Here is a grepped log of it
```
D/OkHttpDownloaderLog(26573): starting file transfer
D/OkHttpDownloaderLog(26573): filetransfer done
D/OkHttpDownloaderLog(26573): pre move file
D/OkHttpDownloaderLog(26573): Renaming file
D/OkHttpDownloaderLog(26573): File renamed
D/OkHttpDownloaderLog(26573): post onSucces
D/OkHttpDownloaderLog(26573): disconnecting
```

**Comment by mokasin** [comment]
I've uninstalled the app completely and installed it again. Now the download does not start. I only get a "download in progress". Also no *OkHttpDownloaderLog* in the logcat.

**Comment by bottiger** [comment]
@mokasin I just reproduced it on my Nexus5. I will look into it tonight. Thank you.

**Comment by bottiger** [comment]
@mokasin I've published 0.128.22, with several improvements to the download manager. It's not perfect yet, but it's moving along. Can you please confirm or deny that it has solved your problem?

**Comment by mokasin** [comment]
@bottiger, now I can download again. But the original issue is not solved. There is not inidication, if a podcast was downloaded or not. Also I the app crashed multiple times when trying to play a stream offline.

**Comment by bottiger** [comment]
@mokasin Right, I see your crash reports. However, I have no idea how you get in that state.

**Regarding episodes not being shown as downloaded**: The download icon should turn into a trash can icon. But I assume it doesn't do that for you :) Are you downloading from the player/playlist or from inside a Feed-window?

**Regarding the crash:** I do see you crash report, but I cannot reproduce it myself. You are also not the only one with the problem :( Just for clarity, can you walk me through exactly how you provoke the crash? Which play button are you pressing?

**Comment by mokasin** [comment]
@bottiger I've tried downloading from from the feed window and the player.
What you can try: I've subscribed to an arbitrary podcast, let's say Cooking Issues. Now I go to the feed view, select an episode (say 210) and pressing the download button. Now I get a 'cannot download' error. I add it to the playlist and again press the download button. Now I get a clock icon and nothing happens. Just playing it works fine however.

Now going to some other arbitrary Podcast, say Raumzeit. Go to an episode (Philae) in the feed view and press the download button. Now the clock icon flashes shortly and it begins the download (I see a circle around the download button). Also the download manager displays this. After the download is completed, I see the download button again. Offline playing does not work.

I can't reproduce the crash at the moment. By the way, do you see my crash report specifically? If yes, how can you identify this?

**Comment by bottiger** [comment]
@mokasin I'll take a look at it. I've also had a problem or two the last few days, but it's hard to reproduce.

Regarding crash reports. I just assumed it was to because there was a crash when someone, using an Xperia phone, pressed the play button. I don't get that many crash reports anymore so I assumed it was you. Every crash report also includes a unique phone id, like "d324cb297bd035e6", but no name, e-mail or other personal information.

You can disable rash reporting if you like, then no data will be shared at all.
