### ISSUE TITLE
F-droid build for 0.142.2 still failing

### ISSUE THREAD

**Issue by est31** [bottiger/SoundWaves#80]
I've tried to build the 0.412.2 version with the f-droid buildsystem, but it appears to still fail.

Apparently it still tries to compile files inside `app/src/main/java/org/bottiger/podcast/player/googlecast` which obviously will fail, and when I remove those files (entirely doable by f-droid) it gives me the two errors:

```
/home/vagrant/build/org.bottiger.podcast/app/src/main/java/org/bottiger/podcast/MediaRouterPlaybackActivity.java:11: error: package org.bottiger.podcast.player.googlecast does not exist
import org.bottiger.podcast.player.googlecast.GoogleCastPlayer;
                                             ^
/home/vagrant/build/org.bottiger.podcast/app/src/main/java/org/bottiger/podcast/webservices/datastore/webplayer/WebPlayerAuthenticator.java:9: error: package org.bottiger.podcast.flavors.MessagingService does not exist
import org.bottiger.podcast.flavors.MessagingService.InstanceIDService;
```

**Comment by bottiger** [comment]
@est31 Thank you for getting back to me. Are you affiliated with F-droid? 

In any case, I am aware of this problem and is working on getting it fixed. The version available on F-droid is very old at the moment, which is a shame. 
However, since I do not have any good way of test building my app like F-droid does the debugging process is a bit slow.

**Comment by est31** [comment]
@bottiger yes, I'm an f-droid contributor.

If you have linux, you can [set up the buildsystem](https://f-droid.org/wiki/page/Installing_the_Server_and_Repo_Tools#Buildserver_Setup) yourself.

In any case I'll try to provide assistance if you have questions about the errors or about how to build apps for f-droid to debug issues.

**Comment by bottiger** [comment]
@est31 Unfortunately I only have windows on my main machine. I may have a few questions for you, but right now I found a few problems which I'll fix first. I'll get back to you when I think I have something that works.

**Comment by bottiger** [comment]
@est31 Can you try to build the current master (free flavor)? I think it should build now.

Thanks.

**Comment by est31** [comment]
@bottiger it fails, look at the log at http://pastebin.com/md6qpH73

**Comment by bottiger** [comment]
@est31 Thank you very much for that. At first glance I have to admit I do not understand the problem. Normally the issue is some kind of dependency on a proprietary google library, but I can't see that it's the case here.

I will need to investigate it tomorrow.

**Comment by bottiger** [comment]
@est31 I have a guess of what the problem might be, but at the moment it's only a guess. I have recently split the project into 3 modules. "app", "soundwavescommon" and "WebPlayer". The "app" module is the app itself, the "WebPlayer" is a simple web based player I'm working a bit on, and the "soundwavescommon" is just some common code.

Everything is open source, but the WebPlayer does require some proprietary libraries from google. The app there is nothing in the WebPlayer which the app itself requires.  In the log it looks like you/F-droid is first building "soundwavescommon" which builds just fine. Then it builds "WebPlayer" which fails, and the it builds the app which fails as well.

I Just found an accidental dependency on the WebPlayer in the app project, which I removed in the master branch. Could you try to rebuild? Unfortunately I have not had time to do some real testing of it yet.

**Comment by est31** [comment]
@bottiger I can confirm that build works with commit 206e8be886442adf5080b5d7adec2eab85b708cf

**Comment by est31** [comment]
Can you do a new release for it (including raising the vercode and vername)? Then its clearer for f-droid than manually specifying a commit.

**Comment by bottiger** [comment]
@est31 I will need to do some more internal testing before pushing a release. I did some changes to the database and I really need to make sure the upgrade works properly in all the cases I can think of :)

But hopefully I can push a new release later today. I will update this issue when it's done.

again - thanks a lot of getting in touch with me.

**Comment by est31** [comment]
Thanks for fixing the issues!

**Comment by bottiger** [comment]
@est31 I've pushed 0.142.4 which hopefully will get the version on F-droid updated.

**Comment by est31** [comment]
@bottiger nope, seems you forgot to bump the version code. Maybe want to make a new tag with a fixed version code?

**Comment by bottiger** [comment]
@est31 What a mess. I have create a new tag/release now. I hope this is final :)

**Comment by est31** [comment]
It works now. Thanks for your help!
